# This is a GNU makefile

# Comment out DEBUG for production build which compresses the
# CSS and javascript files that are served.
DEBUG = 1

hostname = $(shell hostname)

# from running ./configure [--prefix=/my/prefix]
-include config

####################################################
#  CONFIGURATION if file config does not exist
####################################################
# This following can be overridden of changed here
# via include file prefix which may be generated by
# running ./configure --prefix=/my/prefix
PREFIX ?= /usr/local/encap/webLauncher

WS = ws@1.1.1 # This version of ws works
####################################################

built_js_files = $(patsubst %.jsp,%.js,$(wildcard etc/*.jsp))
built_css_files = $(patsubst %.cs,%.css,$(wildcard etc/*.cs))

keys = etc/key.pem etc/cert.pem

built_files = $(sort\
 $(built_js_files)\
 $(built_css_files)\
 $(keys))

js_files = $(sort $(wildcard etc/*.js) $(built_js_files))
css_files = $(sort $(wildcard etc/*.css) $(built_css_files))



# Stuff we install in etc/
etc_files = $(js_files) $(css_files) $(keys)\
 $(wildcard etc/*.htm etc/*.png etc/*.jpg)

BIN = $(PREFIX)/bin
ETC = $(PREFIX)/etc



# We npm install a copy of ws for development
build: $(built_files)
	npm install $(WS)

# ref: http://superuser.com/questions/226192/openssl-without-prompt
$(keys):
	openssl req\
 -new\
 -nodes\
 -x509\
 -newkey rsa:2048\
 -keyout etc/key.pem\
 -subj "/C=US/ST=Denial/L=Blacksburg/O=Dis/CN=$(hostname)" \
 -out etc/cert.pem\
 -days 36500

ifndef DEBUG
%.js: %.jsp
	echo "// This is a generated file" > $@
	yui-compressor --line-break 70 --type js $^ >> $@
%.css: %.cs
	echo "/* This is a generated file */" > $@
	yui-compressor --line-break 70 --type css $^ >> $@
else
%.js: %.jsp
	echo "// This is a generated file" > $@
	cat $^ >> $@
%.css: %.cs
	echo "/* This is a generated file */" > $@
	cat $^ >> $@
endif

mkdirs:
	rm -rf $(ETC) $(BIN) && mkdir -p $(ETC) $(BIN)


# The current version of socket.io seems to be broken when used
# with firefox and chromium-browser.  So we are trying nodejs 'ws'
# WebSockets.

install: mkdirs
	cp  -r $(etc_files) $(ETC)/
	cp webLauncher $(BIN)/
	cd $(BIN)/ && npm install $(WS)
	echo "etc" > $(PREFIX)/encap.exclude
	echo "node_modules" > $(BIN)/encap.exclude

clean:
	rm -rf node_modules config $(built_files)

